<?php
/*
  What is run time Exception
 => In debbugging procees there are three types of debbugging error_get_last
 1.Error
     syntex error or complile time error
	 
 2. Bug 
    It is a error which is not compile time and is not generated by Developer
     That means it will remain hidden from developers points of view but at some
    point(loop whole)	may be useful for a hacker 

=> Developer point of view it may a ok 
=> Tester point of view it is bug
=>All the bugs are generated at Testing (Bug Reporting...)
=>Hence Testing is Also part of Devops
=>Testing is software Role
=>  
    In general Testing two types
 ->1.white box testing :developers will Do
 ->2.Black box testing :Tester will do which developer ignore it

Black box Testing
  1.Manual Testing
  2.Automation Testing using (selenium)
  3.Security Testing (Penitration Testor) (white Hat Hacker) 
  
  => Bug Includes :: content ,spell checking,Degine,Load Time,Heavy Traffic
  sql -injection attack ...etc.
  
  =>Stages of error
  1.Critical
  2.Normal
  3.on prior
  
  Exception::
  ===========
  These are the error which will occurs at run time which mean your programme will
  run very smmoth for few cases but fail at exceptional value.
  such type of Exception only arises due to logical error.
  
=>  Devides by Error  or maths error
=> Index of Range error
=> Maximum Exception Error.

Such exception must be handled and called as exception handling.
  
 
*/    
	
 ?>